Twittex/Twittex/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth

urlpatterns = [
    # Examples:
    # url(r'^$', 'Twittex.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('twittexApp.urls', namespace="twittexApp")),
    url(r'^admin/', include(admin.site.urls)),
]

Twittex/twittexApp/urls.py
from django.shortcuts import render
from django.views import generic
from django.conf import settings
from django.conf.urls import patterns, url, include, static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from twittexApp import views
from django.conf import settings
from django.views.generic.base import TemplateView
from django.contrib.auth.views import password_reset_confirm
from django.contrib.auth.decorators import login_required

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^home/$', views.viewHome, name='home'),
    url(r'^profile/(?P<username>[\w-]+)/$', views.ProfileDetailView, name='profile'),
    url(r'^settings/edit$', (login_required(login_url='/login/'))(views.ProfileEditView.as_view()), name='profileedit'),
    url(r'^messages/$', views.NachrichtenView, name='messages'),
    url(r'^messages/(?P<username>[\w-]+)/$', views.ConversationView, name='conversation'),
    url(r'^sendMsg/$', views.sendMsg, name='sendMsg'),
    url(r'^newPost/$', views.newPost, name='new_post'),
    url(r'^delete/(?P<pk>[A-Za-z0-9\w|\W]+)$', (login_required(login_url='/login/'))(views.DeleteView.as_view()), name='delete'),
    url(r'^search/$', views.search, name='search'),
    url(r'^notification/$', views.viewNotification, name='notifcation'),
    url(r'^followerlist/$', views.viewList, name='list'),
    url(r'^newList/$', (login_required(login_url='/login/'))(views.NewListView.as_view()), name='newList'),
    url(r'^followerlist/(?P<pk>[\w-]+)/$', views.ListDetailView, name='detailList'),
    url(r'^followerlist/(?P<pk>[\w-]+)/edit/$', (login_required(login_url='/login/'))(views.ListEditView.as_view()), name='editList'),
    url(r'^followerlist/(?P<pk>[\w-]+)/delete/$', (login_required(login_url='/login/'))(views.ListDeleteView.as_view()), name='deleteList'),
    url(r'^followerlist/(?P<pk>[\w-]+)/follow/$', views.ListFollowView, name='followList'),
    url(r'^follow/(?P<username>[\w-]+)/$', views.following, name='Follow'),
    url(r'^unfollow/(?P<username>[\w-]+)/$', views.unfollowing, name='Unfollow'),
	url(r'^home/(?P<pk>[\w-]+)/$', views.viewPrivacy, name='viewPrivacy'),
    url(
        r'^login/$',
        'django.contrib.auth.views.login',
        kwargs={'template_name': 'login.html'}
    ),
    url(
        r'^logout/$',
        'django.contrib.auth.views.logout',
        kwargs={'next_page': '/','template_name': 'index.html'}
    ),
    url(
        r'^settings/password_change/$',
        'django.contrib.auth.views.password_change',
        kwargs={'post_change_redirect': 'twittexApp:password_change_done', 'template_name': 'password_change_form.html'}
    ),
    url(
        r'^settings/password_change_done/$',
        'django.contrib.auth.views.password_change_done',
        kwargs={'template_name': 'password_change_done.html'},
        name= 'password_change_done'
    ),
    url(
        r'^password_reset/$',
        'django.contrib.auth.views.password_reset',
        kwargs={'post_reset_redirect': 'twittexApp:password_reset_done', 'template_name': 'password_reset_form.html', 'email_template_name': 'password_reset_email.html'}
    ),
    url(
        r'^password_reset_done/$',
        'django.contrib.auth.views.password_reset_done',
        kwargs={'template_name': 'password_mail_done.html'},
        name= 'password_reset_done'
    ),
    url(
        r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm,
        kwargs={'post_reset_redirect': 'twittexApp:password_reset_complete', 'template_name': 'password_reset_form.html'},
        name='password_reset_confirm'
    ),
    url(
        r'^reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        kwargs={'template_name': 'password_reset_done.html'},
        name='password_reset_complete'
    ),
    url(r'^contact/send/$', views.sendmail),
    url(r'^thanks/$', TemplateView.as_view(template_name='thanks.html'), name='thanks'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^impressum/$', TemplateView.as_view(template_name='impressum.html'), name='impressum'),
    url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
    url(r'^api/post/$', views.apiPost, name='api_post'),
    url(r'^api/test/$', TemplateView.as_view(template_name = 'apiPost_test.html'), name='apiTest'),
)

if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        (r'media/(?P<path>.*)', 'serve', {'document_root': settings.MEDIA_ROOT}),
)

Twittex/twittexApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from datetime import datetime


class Posts(models.Model):
    Post_Privacy_CHOICES = (
    ('Pub', 'Public'),
    ('OF', 'only Followers'),
    ('OM', 'only Me'),
)
    inhalt = models.CharField(max_length=140)
    hashtags = models.CharField(max_length=100)
    datum = models.DateTimeField(default=datetime.now, blank=True)
    autor = models.ForeignKey(User)
    mentioned = models.ManyToManyField(User, related_name='mentioned')
    privacy= models.CharField(max_length = 3,choices=Post_Privacy_CHOICES,default='Pub')


class Conversation(models.Model):
    absender = models.ForeignKey(User, related_name='absender')
    empfaenger = models.ForeignKey(User)
    inhalt = models.CharField(max_length=140)
    datum = models.DateTimeField(default=datetime.now, blank=True)

class EmailForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField()
    subject = forms.CharField(max_length=255)
    message = forms.CharField()


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    desc = models.CharField(max_length = 140, blank=True, null=True)
    picture = models.ImageField(upload_to='profile_pictures', blank=True, default='no_photo.jpg')
    mentioned_count = models.IntegerField(default=0)
    follows = models.ManyToManyField('UserProfile', related_name='followed_by')
    privacy = models.BooleanField(default=False)
    # false fuer alle sichtbar
    # true nur fuer die ich folge sichbar

    def __unicode__(self):
        return self.user.username

    def getPicture(self):
        if not self.picture:
            return '/media/no_photo.jpg'
        else:
            return self.picture.url


class List(models.Model):
    title = models.CharField(max_length = 25)
    admin = models.ForeignKey(User)
    userlist = models.ManyToManyField(User, related_name='userlist', blank=True)

Twittex/twittexApp/views.py
from pathlib import _Accessor
from django.db.models.query_utils import Q
from django.shortcuts import render, redirect, RequestContext, render_to_response, Http404
from itertools import chain
from django.db.models import Q
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from twittexApp.forms import UserCreationForm, AuthenticationForm, UserForm, UserProfileForm, PostsName, ListForm
from twittexApp.models import Posts, User, UserProfile, EmailForm, models, List, Conversation
from django.http import HttpResponse, HttpResponseRedirect
import smtplib
from django.core.mail import send_mail
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
@login_required(login_url='/login/')
def viewPrivacy(request,pk):
    cname= request.POST.get('priv')
    userp= request.user
    post = Posts.objects.get(id=pk)
    post.privacy= cname
    post.save()
    return redirect('/profile/' +userp.username )
	
def IndexView(request):
    if request.user.is_authenticated():
        return redirect('/home')
    else:
        return render_to_response('index.html')


def register(request):  
    # Like before, get the request's context.
    context = RequestContext(request)

    # will change when registration done
    registered = False

    # User input
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # if valid save
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            # create but dont save yet
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # now save
            profile.save()

            # say true for template
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    # provide forms
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context
    return render_to_response(
        'register.html',
        {'user_form': user_form, 'profile_form': profile_form, 'registered': registered},
        context)

@login_required(login_url='/login/')
def ProfileDetailView(request, username):
    posts = Posts.objects.all().order_by('-datum')
    user = User.objects.get(username=username)
    follower= request.user.userprofile.follows.all()
    if len(follower) != 0 and user.userprofile in follower:
        follow= follower.get(user= user)
    else:
        follow = None

    privacy = 'yes'

    if username != request.user.username:
        if user.userprofile.privacy:
            if request.user.userprofile in user.userprofile.follows.all():
                privacy = 'yes'
            else:
                privacy = 'no'

    yes= 'yes'
    no= 'no'
    if follow is None :
        follow= 'no'
    else:
        follow = 'yes'
	
    for p in posts:
        followed = p.autor.userprofile.followed_by.all()
        if p.privacy == 'OM' and p.autor != request.user:
            posts = posts.exclude(id= p.id)
        if p.privacy == 'OF' and request.user.userprofile not in followed and request.user != p.autor:
                posts = posts.exclude(id= p.id)
    return render_to_response('profile.html', {'object_list': posts, 'user': user, 'request': request, 'followlist': follower, 'follow':follow, 'privacy':privacy, 'yes': yes, 'no': no}, context_instance=RequestContext(request))


class ProfileEditView(UpdateView):
    template_name = 'editprofile.html'
    success_url = '/'
    fields = ['desc', 'picture', 'privacy']

    def get_object(self):
        return UserProfile.objects.get(user=self.request.user)

@login_required(login_url='/login/')
def viewList(request):
    list=List.objects.all()
    return render(request,'list.html',
    {'object_list': list})

@login_required(login_url='/login/')
def ListDetailView(request, pk):
    list = List.objects.get(id=pk)
    userlist = list.userlist.all()
    return render_to_response('listdetail.html', {'list': list, 'userlist': userlist,'request': request}, context_instance=RequestContext(request))


class NewListView(CreateView):
    template_name = 'newList.html'
    model = List
    success_url = '/followerlist/'
    form_class = ListForm


class ListEditView(UpdateView):
    template_name = 'editlist.html'
    fields = ['title', 'userlist']
    model = List

    def get_success_url(self):
        return reverse('twittexApp:list')


class ListDeleteView(DeleteView):
    template_name = 'delete_comfirm.html'
    success_url = '/home/'
    model = List

    def delete(self, request, *args, **kwargs):
       self.object = self.get_object()
       if self.object.admin == request.user:
          self.object.delete()
          success_url = self.get_success_url()
          return HttpResponseRedirect(success_url)
       else:
          raise Http404 #or return HttpResponse('404_url')

@login_required(login_url='/login/')
def ListFollowView(request, pk):
    list = List.objects.get(id = pk)
    userlist = list.userlist.all()
    for user in userlist:
        request.user.userprofile.follows.add(user.userprofile)
    return redirect('/home/')


# called by submit post
def newPost(request):
    if request.method == "POST":
        content = str(request.POST.get('inhalt'))
        #hashtag search from http://stackoverflow.com/questions/6331497
        hashtags = set()
        mentioned = set()
        #links erkennen
        for tag in content.split():
            if tag.startswith("#"):
                strippedTag = tag.strip("#")
                hashtags.add(strippedTag)
                content = content.replace(tag, "<a href='/search/?q="+strippedTag+"'>"+tag+"</a>")
            if tag.startswith("@"):
                strippedTag = tag.strip("@")
                mentioned.add(strippedTag)
                content = content.replace(tag, "<a href='/profile/"+strippedTag+"'>"+tag+"</a>")
            if (tag.startswith("http://") | tag.startswith("https://")):
                content = content.replace(tag, "<a href='"+tag+"'>"+tag+"</a>")
            if tag.startswith("www."):
                content = content.replace(tag, "<a href='http://"+tag+"'>"+tag+"</a>")

        p = Posts(inhalt=content, hashtags=str(hashtags))

        if request.user.is_authenticated():
            p.autor = request.user
        else:
            usr = str(request.POST.get('username'))
            pswd = str(request.POST.get('password'))

            user = authenticate(username=usr, password=pswd)
            if user is not None:
                p.autor = User.objects.get(username = str(request.POST.get('username')))
            else:
                return HttpResponse('invalid user / pwd'+usr+pswd)

        p.save()

        for username in mentioned:
            user = User.objects.get(username=username)
            if (user.username == username):
                user.userprofile.mentioned_count += 1
                user.userprofile.save()
                p.mentioned.add(user)
                p.save()

        p.save()
        return redirect('/home/')
    else:
        return HttpResponse('Post method required')


class DeleteView(PostsName, DeleteView):
    template_name = 'delete_comfirm.html'
    success_url = '/home/'

    def delete(self, request, *args, **kwargs):
       self.object = self.get_object()
       if self.object.autor == request.user:
          self.object.delete()
          success_url = self.get_success_url()
          return HttpResponseRedirect(success_url)
       else:
          raise Http404 #or return HttpResponse('404_url')


def sendmail(request):
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            content = name + " " + "<" + email + ">" + " send the following message: \n \n " + message
            send_mail(subject, content, email, ['twittexsn@gmail.com'])
            return redirect('/thanks/')
        else:
            return redirect('/contact/')

@login_required(login_url='/login/')
def NachrichtenView(request):
    context_object_name = 'conversations'

    user = request.user
    eingang = Conversation.objects.filter(empfaenger=user).distinct('absender')
    ausgang = Conversation.objects.filter(absender=user).distinct('empfaenger')

    return render_to_response('nachrichten.html', {'eingang': eingang, 'ausgang': ausgang,'request': request}, context_instance=RequestContext(request))

@login_required(login_url='/login/')
def sendMsg(request):
    if request.method == 'POST':
        inhalt = request.POST['inhalt']
        empfaenger = request.POST['empfaenger']
        absender = request.user

        if not (User.objects.filter(username=empfaenger).exists()):
            # user not found
            return redirect('/home/')

        absender = User.objects.get(username=absender)
        empfaenger = User.objects.get(username=empfaenger)

        msg = Conversation(absender=absender, empfaenger=empfaenger, inhalt=inhalt)
        msg.save()

        return redirect('/messages/' + empfaenger.username)
    else:
        return render(request,
            'newMsg.html')

@login_required(login_url='/login/')
def ConversationView(request, username):
    mainuser = request.user

    if not (User.objects.filter(username=username).exists()):
        return redirect('/messages/')

Twittex/twittexApp/templates/apiPost_test.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="container">
						<form action="/api/post/" method="post">
								{% csrf_token %}
								username: 
								<input type="text" class="form-control" id="username" name="username">
								password:
								<textarea class="form-control" rows="1" id="password" name="password"></textarea>
								<textarea class="form-control" rows="5" id="inhalt" name="inhalt"></textarea></br>
								<button type="submit" class="btn btn-primary btn-block">Post!</button>
							<br/>
							</form>
						</div>
						{% endblock content %}

Twittex/twittexApp/templates/editlist.html
{% extends "base.html" %}
{% load static from staticfiles %}
     {% block extra_head %}
        <link href="{% static "css/login.css" %}" rel="stylesheet">
     {% endblock %}

{% block content %}
<div class="container">
    <h1 class="well">Edit Followerlist</h1>
    <form method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        Choose User by pressing CTR/STRG+Click on User!
        {% for field in form %}
            <div class="form-group">
            {{ field.errors }}
            <p>{{ field.label_tag }}</p>
            <p>{{ field }}</p>
            </div>
        {% endfor %}
        <input type="submit" value="Edit my Followerlist" />
    </form>
</div>
{% endblock content %}

Twittex/twittexApp/templates/listdetail.html
{% extends "base.html" %}
{% load static from staticfiles %}
     {% block extra_head %}
        <link href="{% static "css/login.css" %}" rel="stylesheet">
     {% endblock %}

{% block content %}
<div class="container">
<h1 class="well text-center">{{ list.title }}</h1>
            <div>Admin: {{ list.admin.username }}</div>
            <div>Userlist:</div>
            <ol>
            {% for user in userlist %}
            <li>{{ user.username }}</li>
            {% endfor %}
            </ol>
            <a href="follow/" class="btn btn-primary btn-sm">Follow {{ list.title }}</a>
            {% if list.admin == request.user %}
            <a href="edit/" class="btn btn-primary btn-sm">Edit {{ list.title }}/Add Users</a>
            <a href="delete/" class="btn btn-primary btn-sm">Delete {{ list.title }}</a>
            {% endif %}
</div>
{% endblock content %}

Twittex/twittexApp/templates/nachrichten.html
{% extends "base.html" %}

{% block content %}

<div class="container">
<h1 class="well">Your Conversation's</h1>


<ul class="nav nav-tabs">
    <li role="presentation" class="active"><a href="#item1" data-toggle="tab">Inbox</a></li>
    <li role="presentation"><a href="#item2" data-toggle="tab">Send Message's</a></li>
</ul>

<div class="tab-content">
<div class="tab-pane active" id="item1">
<table class="table">
         <thead>
                 <tr>
                         <th>From User</th>
                         <th>Latest Date</th>
                  </tr>
        </thead>
        <tbody>
            {% for conv in eingang %}
                 <tr>
                     <td><a href="{{ conv.absender.username }}">{{ conv.absender.username }}</a></td>
                     <td> {{ conv.datum }}</td>
                 </tr>
            {% endfor %}
        </tbody>
</table></div>
<div class="tab-pane" id="item2">
<table class="table">
         <thead>
                 <tr>
                         <th>To User</th>
                         <th>Latest Date</th>
                  </tr>
        </thead>
        <tbody>
            {% for conv in ausgang %}
                 <tr>
                     <td><a href="{{ conv.empfaenger.username }}">{{ conv.empfaenger.username }}</a></td>
                     <td> {{ conv.datum }}</td>
                 </tr>
            {% endfor %}
        </tbody>
</table>
</div>
</div>

<a href="/sendMsg" class="btn btn-primary btn-sm dropdown-toggle btn-block" role="button">Send a Message</a>
</div>
{% endblock %}

Twittex/twittexApp/templates/newMsg.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<h1 class="well">Send Message</h1>
	<form method="post" class="form" enctype="multipart/form-data">
	    {% csrf_token %}

	    <div class="form-group">
	        <input type="text" class="form-control" id="empfaenger" name="empfaenger" placeholder="Reciepment" required="" autofocus="" />
	        <input type="text" class="form-control" id="inhalt" name="inhalt" placeholder="Inhalt" required=""/>
	    </div>
	    <input type="submit" value="Send Messages" />
	</form>
</div>
{% endblock %}

Twittex/twittexApp/templates/newPost.html
<form action="newPost/" method="post">
											{{ form.as_p }}
										<button type="submit" class="btn btn-default btn-block">Submit</button>
									</form>

Twittex/twittexApp/templates/notification.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extra_head %}
	<link href="{% static "css/home.css" %}" rel="stylesheet">
	{% endblock %}   
{% block content %}

<div class="container">
<h1 class="well text-center">Who mentioned you on Twittex?</h1>
            {% for posts in postss %}
				<div class="well well-sm">
					<table>
						<tr>
							<td><a href="/profile/{{ posts.autor.username }}">@{{ posts.autor.username }}</a><br/>
                			{{ posts.inhalt|safe }}
                			</td>
						</tr>
					</table>
				</div>
            {% endfor %}
</div>
{% endblock content %}

Twittex/twittexApp/templates/password_change_done.html
{% extends "base.html" %}
{% block content %}
    Your password has been changed successfully. Go back to the
    <a href="/">main page</a>.
{% endblock %}

Twittex/twittexApp/templates/password_change_form.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<h1 class="well">Edit Password</h1>
<form method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
        {{ field.errors }}
        {{ field.label_tag }}
        {{ field }}
        </div>
    {% endfor %}
    <input type="submit" class="btn btn-info" value="Change my Password" />
    <a href="/profile/{{ request.user.username }}" class="btn btn-info" role="button">Back to the Profile</a>
</form>
</div>
{% endblock content %}

Twittex/twittexApp/templates/password_reset_done.html
{% extends "base.html" %}
{% block content %}

<div class="container">

<h1 class="well">Reset Password</h1>

    Your password has been changed successfully. Please re-login with your new credentials
    <a href="/login/">login</a> or go back to the
    <a href="/">main page</a>
</div>
{% endblock %}

Twittex/twittexApp/templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}/reset/{{uid}}/{{token}}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

Twittex/twittexApp/templates/profile.html
{% extends "base.html" %}

{% block content %}

<br/>
<div class="container-fluid">
	<div class="well text-center">
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		        {% if user.username = request.user.username %}
		            <h1>Welcome to your profile!</h1>
		        {% else %}
				    <h1>Welcome to {{ user.username }}'s profile!</h1>
		        {% endif %}
		    </div>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
			<div class="well">
				<img class="img-responsive img-rounded  center-block" src="{{ user.userprofile.getPicture }}" alt="Profile Picture"/>
				</br>
				<p>Description:<br/>{{ user.userprofile.desc }}<br/><br/></p>
				{% if request.user = user %}
	    		<a href="/settings/edit" class="btn btn-primary btn-sm dropdown-toggle btn-block" role="button">Edit Profile</a>
				<a href="/settings/password_change" class="btn btn-primary btn-sm dropdown-toggle btn-block" role="button">Edit Password</a>
				{% elif follow = no %}
				<a href={% url 'twittexApp:Follow' user.username %} class="btn btn-primary btn-sm dropdown-toggle btn-block" role="button">Follow</a>
				{%elif follow = yes%}
				<a href={% url 'twittexApp:Unfollow' user.username %}  class="btn btn-primary btn-sm dropdown-toggle btn-block" role="button">Unfollow</a>
				{% endif %}
			</div>
		</div>
		<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
			<div class="well well-sm">
				<table class="table">
					<thead>
					<tr>
						<td>
							<h2>@{{ user.username }}'s posts:</h2>
							{% if privacy = yes %}
							{% for posts in object_list %}
							{% if posts.autor = user  %}</td>
					</tr>
					</thead>
					<tr class="info">
								<td><a href="/profile/{{ user.username }}">@{{ user.username }}</a> wrote at {{ posts.datum }}
								<div class="Post">{{ posts.inhalt|safe }}</div>
								{% if request.user = user %}
								<form action={% url 'twittexApp:viewPrivacy' posts.id %} method="post"> {% csrf_token %}
								<p> 
									{% if posts.privacy = 'Pub' %}
								<select name="priv"> 
								        <option value="Pub">Public</option> 
								        <option value="OF">Only Followers</option> 
								        <option value="OM">Only Me</option> 
								</select> 
								<input type="submit" value="Change" /> 
								</p> 

								{% elif posts.privacy = 'OF' %}
								<select name="priv"> 
								        <option value="Pub">Public</option> 
								        <option value="OF" selected>Only Followers</option> 
								        <option value="OM">Only Me</option> 
								</select> 
								<input type="submit" value="Change" /> 
								</p> 

								{% else %}
								<select name="priv"> 
								        <option value="Pub">Public</option> 
								        <option value="OF" >Only Followers</option> 
								        <option value="OM"selected>Only Me</option> 
								</select> 
								<input type="submit" value="Change" /> 
								</p> 
								

								</select>
								{% endif %}
								</form> 
								<a href="/delete/{{ posts.id }}" class="btn btn-primary btn-sm">Delete</a>
								{% endif %}
								</td>
							</tr>
					<tr><td></td></tr>
				
					{% endif %}
				{% endfor %}
				</table>
				{% else %}
				<table>
					<tr>
						<td>
							<div>
								Sorry, but only {{ user }} and who he is following can see those posts :/
							</div>
						</td>
					</tr>
				</table>
			{% endif %}
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		</br>
	</div>
</div>

{% endblock content %}

Twittex/twittexApp/templates/register.html
{% extends "base.html" %}
{% load static from staticfiles %}
     {% block extra_head %}
        <link href="{% static "css/login.css" %}" rel="stylesheet">
     {% endblock %}   

{% block content %}
        {% if registered %}
        <br/>
        <div class="container">
            <div class="jumbotron"><h1>Thank you for registering!</h1>
                <h2><a href="/login">Go here for Login!</a><br /></h2></div>
             
        </div>
       
        {% else %}
        <div class = "container">
            <div class="wrapper">
                <form id="user_form" class="form-signin" method="post" action="/register/" enctype="multipart/form-data">
                    {% csrf_token %}      
                    <h3 class="form-signin-heading"> Yeah! Just one more step to register!</h3>
                     <hr class="colorgraph"><br>
                  
                    <input type="text" class="form-control" id="id_username" name="username" placeholder="Username" required="" autofocus="" />

                    <input id="id_email" class="form-control" maxlength="254" name="email" placeholder="E-Mail" required="" type="email" /><br/>

                    <input id="id_password" name="password" type="password" placeholder="Password" class="form-control" />

                    <input id="id_password2" name="password2" placeholder="Confirm password" type="password" class="form-control" />

                    <input id="id_desc" maxlength="140" name="desc" type="text" class="form-control" placeholder="(Optional) Add a description about yourself"/><br/>

                    <p>Add a profile picture:
                    <input id="id_picture" name="picture" class="form-control" type="file" placeholder="(Optional) Upload a profile picture"/></p>

                    <input type="hidden" name="next" value="/home" />
                    <button class="btn btn-lg btn-primary btn-block"  name="Submit" value="Login" type="Submit">Sign Up</button>             
                </form>         
            </div>
        </div>
        {% endif %}
{% endblock content %}

Twittex/twittexApp/templates/thanks.html
{% extends "base.html" %}
{% block title %}Thanks!{% endblock title %}
    {% block content %}
	    <div class="container">
	  		<h1>Thank you for your E-Mail!</h1>
	  		<p>We will help you soon</p>
	  		<a href="/contact"  class="btn btn-info" role="button">Click to Continue</a>
		</div>
		{% endblock content %}